### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by lbittarello** [Quantco/pre-commit-insert-license#12]
Would it be possible to create a bot to automatically update the final year in the license? Just so we don't get CI failures unnecessarily. :)

**Comment by ThomasMarwitzQC** [comment]
Do you refer to the ci failure that was introduced when 2023 ended and 2024 began?

**Comment by jtilly** [comment]
@lbittarello when you just re-run CI on an existing code base, CI will be green even if on New Year's Day: see, e.g., https://github.com/Quantco/quantcore.geo/actions/runs/7383898495/job/20583083902 (which I just re-ran before you merged your PR).

For each file, `insert-license-header` only complains if the year in the header is behind the last modification date (based on the git history of the file).

**Comment by ThomasMarwitzQC** [comment]
The reason why this was initially failing on New Year's Day is that the `checkout` github action did only checkout the last commit, suggesting that every file was modified on this day. 

That's why `fetch-depth: 0` needs to be set in pre-commit CI.

**Comment by lbittarello** [comment]
Thanks, I was aware. :)

I was just thinking that it'd be easier to have a bot swoop in on 1 January and fix the license across all files in one go rather than relying on a precommit hook to fix files as we modify them.

**Comment by ThomasMarwitzQC** [comment]
Looping in @xhochy 

I could definitely create such a bot, I'm just not sure if it's worth the effort

**Comment by xhochy** [comment]
The bot seems a bit useless to me. We should make sure the CI never fails. Otherwise, we will have failing CI until the bot has come around. 

Yearly runs of a sweep are not likely to work. They happen so seldomly, it is more likely that they break because the infrastructure is out of date than they will actually succeed.
